#!/usr/bin/env python3
"""Build two isolated QA account previews from the exact signed 2.4.9 APK.

The owner signing key is never read. Each preview gets a separate package id and
is signed with a disposable QA key generated by the workflow. Only classes3.dex
and AndroidManifest.xml are changed; all other APK entries are preserved.
"""
import hashlib, json, os, re, shutil, struct, subprocess, zipfile
from pathlib import Path

BASE_SHA = "0ed539e8fe58dee7a4f3220673a29f6ad8a29b834caae34ac7d779dc45f26332"
BASE_APK = Path(os.environ.get("ACCOUNT_BASE_APK", "account-full251/baseline249.apk"))
SOURCE = Path("account-full251/AccountScreen251.java")
OUT = Path("account-full251/releases")
WORK = Path("account-full251/.build")
OUT.mkdir(parents=True, exist_ok=True)
if WORK.exists():
    shutil.rmtree(WORK)
WORK.mkdir(parents=True)

assert BASE_APK.is_file(), f"Missing baseline: {BASE_APK}"
assert hashlib.sha256(BASE_APK.read_bytes()).hexdigest() == BASE_SHA, "Wrong 2.4.9 baseline"
assert SOURCE.is_file(), "Missing AccountScreen251.java"

sdk = Path(os.environ["ANDROID_HOME"])
platforms = []
for p in (sdk / "platforms").glob("android-*"):
    m = re.fullmatch(r"android-(\d+)", p.name)
    if m:
        platforms.append((int(m.group(1)), p))
platforms.sort()
assert platforms, "Android SDK platform missing"
android = platforms[-1][1] / "android.jar"
bts = sorted((sdk / "build-tools").glob("*"), key=lambda p: [int(x) for x in re.findall(r"\d+", p.name)])
assert bts, "Android build-tools missing"
bt = bts[-1]

def run(*args, env=None, capture=False):
    cmd = [str(x) for x in args]
    if capture:
        return subprocess.check_output(cmd, text=True, env=env)
    subprocess.run(cmd, check=True, env=env)
    return ""

def zread(z, item):
    info = z.getinfo(item) if isinstance(item, str) else item
    with z.open(info) as fp:
        fp._expected_crc = None
        return fp.read()

bridge_template = '''package eu.svoyi.nativeapp;
import android.app.Activity;
import org.json.JSONObject;
final class Account251Bridge {
  static void apply(Activity a, JSONObject m) { AccountScreen251.apply(a, m, VARIANT); }
}
'''

VARIANTS = [
    {
        "slug": "site",
        "variant": 0,
        "package": "eu.svoyi.qa.accountsite",
        "label": "Свої — Account Site Match",
        "filename": "Svoyi-Account-Site-Match-2.5.1-QA.apk",
    },
    {
        "slug": "plus",
        "variant": 1,
        "package": "eu.svoyi.qa.accountplus",
        "label": "Свої — Account Plus",
        "filename": "Svoyi-Account-Plus-2.5.1-QA.apk",
    },
]

def readlen8(d, p):
    n = d[p]; p += 1
    if n & 128:
        n = ((n & 127) << 8) | d[p]; p += 1
    return n, p

def readlen16(d, p):
    n = struct.unpack_from('<H', d, p)[0]; p += 2
    if n & 32768:
        n = ((n & 32767) << 16) | struct.unpack_from('<H', d, p)[0]; p += 2
    return n, p

def put8(n):
    return bytes([128 | (n >> 8), n & 255]) if n >= 128 else bytes([n])

def put16(n):
    return struct.pack('<HH', 32768 | (n >> 16), n & 65535) if n >= 32768 else struct.pack('<H', n)

def rewrite_manifest(data: bytes, package: str, label: str) -> bytes:
    chunks = []
    pos = 8
    strings = []
    pool_index = None
    utf8 = False
    flags = 0
    while pos < len(data):
        typ, head, size = struct.unpack_from('<HHI', data, pos)
        raw = bytearray(data[pos:pos+size])
        chunks.append([typ, head, raw])
        if typ == 1:
            pool_index = len(chunks) - 1
            count, styles, flags, start, style_start = struct.unpack_from('<5I', raw, 8)
            utf8 = bool(flags & 256)
            assert styles == 0, "Styled manifest string pool unsupported"
            for i in range(count):
                q = start + struct.unpack_from('<I', raw, head + i*4)[0]
                if utf8:
                    _, q = readlen8(raw, q); n, q = readlen8(raw, q)
                    s = bytes(raw[q:q+n]).decode('utf8')
                else:
                    n, q = readlen16(raw, q)
                    s = bytes(raw[q:q+2*n]).decode('utf-16-le')
                strings.append(s)
        pos += size
    assert pos == len(data) and pool_index is not None

    old_package = "eu.svoyi.nativeapp"
    for typ, head, raw in chunks:
        if typ != 0x102:
            continue
        ns, name_idx, attr_start, attr_step, attr_count, *_ = struct.unpack_from('<IIHHHHHH', raw, head)
        element = strings[name_idx]
        for i in range(attr_count):
            off = head + attr_start + i*attr_step
            ans, aname_idx, araw, sz, zero, kind, val = struct.unpack_from('<IIIHBBI', raw, off)
            aname = strings[aname_idx]
            if kind != 3 or val >= len(strings):
                continue
            current = strings[val]
            new = None
            if element == 'manifest' and aname == 'package':
                new = package
            elif aname in {'authorities', 'permission', 'readPermission', 'writePermission'} and current.startswith(old_package):
                new = package + current[len(old_package):]
            elif element in {'permission', 'uses-permission', 'uses-permission-sdk-23'} and aname == 'name' and current.startswith(old_package):
                new = package + current[len(old_package):]
            elif element == 'application' and aname == 'label':
                new = label
            if new is not None:
                strings[val] = new

    blob = bytearray(); offsets = []
    for s in strings:
        offsets.append(len(blob)); u = s.encode('utf-16-le')
        if utf8:
            b = s.encode('utf8'); blob += put8(len(u)//2) + put8(len(b)) + b + b'\0'
        else:
            blob += put16(len(u)//2) + u + b'\0\0'
    while len(blob) % 4:
        blob.append(0)
    start = 28 + 4*len(strings)
    pool = struct.pack('<HHI5I', 1, 28, start+len(blob), len(strings), 0, flags & ~1, start, 0)
    pool += struct.pack('<' + 'I'*len(strings), *offsets) + blob
    chunks[pool_index][2] = pool
    payload = b''.join(bytes(raw) for _, _, raw in chunks)
    return struct.pack('<HHI', 3, 8, 8+len(payload)) + payload

def compile_helpers(variant: int, dst: Path):
    if dst.exists(): shutil.rmtree(dst)
    (dst / "classes").mkdir(parents=True)
    (dst / "dex").mkdir()
    (dst / "helper-smali").mkdir()
    bridge = dst / "Account251Bridge.java"
    bridge.write_text(bridge_template.replace("VARIANT", str(variant)), encoding="utf-8")
    run('javac', '-source', '8', '-target', '8', '-cp', android, '-d', dst/'classes', SOURCE, bridge)
    class_files = list((dst/'classes').rglob('*.class'))
    assert any(p.name.startswith('AccountScreen251') for p in class_files)
    assert any(p.name == 'Account251Bridge.class' for p in class_files)
    run(bt/'d8', '--min-api', '26', '--lib', android, '--output', dst/'dex', *class_files)
    run('baksmali', 'disassemble', dst/'dex/classes.dex', '-o', dst/'helper-smali')

def patch_dex(variant: int, build: Path) -> bytes:
    z = zipfile.ZipFile(BASE_APK)
    original = build / "original.dex"
    original.write_bytes(zread(z, 'classes3.dex'))
    smali = build / "smali"
    run('baksmali', 'disassemble', original, '-o', smali)
    helper_dir = build / "compiled"
    compile_helpers(variant, helper_dir)

    target = smali / 'eu/svoyi/nativeapp/Batch20Ui.smali'
    assert target.is_file(), "Batch20Ui missing from 2.4.9 classes3.dex"
    src = target.read_text(encoding='utf-8')
    blocks = list(re.finditer(r'(?ms)^\.method[^\n]*\n.*?^\.end method', src))
    sig = 'remember(Landroid/app/Activity;Lorg/json/JSONObject;)V'
    selected = [m for m in blocks if m.group().splitlines()[0].endswith(sig)]
    assert len(selected) == 1, f"remember method count: {len(selected)}"
    m = selected[0]; old = m.group()
    hook = '    invoke-static {p0, p1}, Leu/svoyi/nativeapp/Account251Bridge;->apply(Landroid/app/Activity;Lorg/json/JSONObject;)V\n'
    assert 'Account251Bridge;->apply' not in old
    returns = old.count('    return-void')
    assert returns >= 1
    new = old.replace('    return-void', hook + '    return-void')
    target.write_text(src[:m.start()] + new + src[m.end():], encoding='utf-8')

    helper_smali = helper_dir / 'helper-smali'
    added = []
    for p in helper_smali.rglob('*.smali'):
        rel = p.relative_to(helper_smali)
        dest = smali / rel
        if dest.exists():
            if dest.read_bytes() == p.read_bytes():
                continue
            raise AssertionError(f"Unexpected non-identical helper collision: {rel}")
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(p, dest)
        added.append(str(rel))
    assert any('AccountScreen251' in x for x in added)
    assert any('Account251Bridge' in x for x in added)
    outdex = build / 'classes3.dex'
    run('smali', 'assemble', smali, '-o', outdex)
    return outdex.read_bytes()

zbase = zipfile.ZipFile(BASE_APK)
base_manifest = zread(zbase, 'AndroidManifest.xml')
results = []
password = "svoyi-qa-account-251"
keystore = WORK / 'account-qa.p12'
env = dict(os.environ, QA_SIGNING_PASSWORD=password)
run('keytool', '-genkeypair', '-keystore', keystore, '-storetype', 'PKCS12', '-storepass', password,
    '-keypass', password, '-alias', 'accountqa', '-keyalg', 'RSA', '-keysize', '3072', '-validity', '3650',
    '-dname', 'CN=Svoyi Account QA 2.5.1', env=env)

for cfg in VARIANTS:
    build = WORK / cfg['slug']; build.mkdir(parents=True)
    dex_bytes = patch_dex(cfg['variant'], build)
    manifest = rewrite_manifest(base_manifest, cfg['package'], cfg['label'])
    unsigned = build / 'unsigned.apk'
    with zipfile.ZipFile(unsigned, 'w', zipfile.ZIP_DEFLATED) as out:
        for info in zbase.infolist():
            if info.filename.startswith('META-INF/'):
                continue
            data = zread(zbase, info)
            if info.filename == 'classes3.dex': data = dex_bytes
            elif info.filename == 'AndroidManifest.xml': data = manifest
            out.writestr(info, data)
    aligned = build / 'aligned.apk'
    run(bt/'zipalign', '-f', '4', unsigned, aligned)
    final = OUT / cfg['filename']
    run(bt/'apksigner', 'sign', '--ks', keystore, '--ks-key-alias', 'accountqa', '--ks-pass', 'env:QA_SIGNING_PASSWORD',
        '--out', final, aligned, env=env)
    verify = run(bt/'apksigner', 'verify', '--verbose', '--print-certs', final, capture=True)
    badging = run(bt/'aapt', 'dump', 'badging', final, capture=True)
    assert cfg['package'] in badging, badging[:500]
    assert 'eu.svoyi.nativeapp.MainActivity' in badging, "MainActivity class name changed unexpectedly"
    sha = hashlib.sha256(final.read_bytes()).hexdigest()
    results.append({
        'variant': cfg['slug'], 'package': cfg['package'], 'filename': cfg['filename'],
        'sha256': sha, 'bytes': final.stat().st_size,
        'signature_verified': True,
        'baseline_sha256': BASE_SHA,
        'hook': 'Batch20Ui.remember -> Account251Bridge.apply',
        'owner_key_used': False,
    })
    (OUT / (cfg['slug'] + '-signature.txt')).write_text(verify, encoding='utf-8')
    (OUT / (cfg['slug'] + '-badging.txt')).write_text(badging, encoding='utf-8')

(OUT / 'SHA256SUMS.txt').write_text(''.join(f"{x['sha256']}  {x['filename']}\n" for x in results), encoding='utf-8')
(OUT / 'build-manifest.json').write_text(json.dumps({
    'version': '2.5.1-account-preview', 'baseline': str(BASE_APK), 'baseline_sha256': BASE_SHA,
    'source_branch': 'android-account-full', 'source_renderer': str(SOURCE),
    'main_package_modified': False, 'server_changed': False, 'private_owner_signing_key_accessed': False,
    'results': results,
}, ensure_ascii=False, indent=2), encoding='utf-8')
print(json.dumps(results, ensure_ascii=False, indent=2))
